version: "3.8"
name: brethren
services:
  front:
    build: ./frontend
    ports:
      - "20014:80"
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    env_file:
      - ./backend/.env.dist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./backend
    env_file:
      - ./backend/.env.dist
    depends_on:
      postgres:
        condition: service_healthy

  flag-service:
    build: ./flag-service
    depends_on:
      postgres:
        condition: service_healthy