version: '3.8'

services:
  web:
    build: .
    ports:
      - "20019:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/weather_db
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./init.sql:/app/init.sql
    restart: always
    pids_limit: 100
    mem_limit: 512M
    cpus: 2
    stop_grace_period: 0s

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    pids_limit: 100
    mem_limit: 512M
    cpus: 2
    stop_grace_period: 0s

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    pids_limit: 100
    mem_limit: 512M
    cpus: 2
    stop_grace_period: 0s
