version: '2.4'

services:
  
    backend:
        build: ./backend/
        restart: always
        environment:
          - FLAG=tctf{REDACTED}
        pids_limit: 500
        mem_limit: 1G
        cpus: 2
        volumes:
          - ./repair_code:/repair_code:ro
        stop_grace_period: 0s
  
    printer:
        build: ./printer
        restart: always
        stop_grace_period: 0s
        volumes:
          - ./repair_code:/repair_code:ro
        scale: 3
        healthcheck:
          test: "curl -fail --max-time 5 http://localhost:3000/ping || exit 1"
          interval: 60s
          timeout: 10s
          start_period: 10s
          retries: 5

    nginx:
        restart: always
        image: nginx:latest
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/static:/var/www/html:ro
        ports:
          - "20020:80"
        depends_on:
          - internal-balancer

    internal-balancer:
        image: nginx:latest
        volumes:
          - ./nginx/internal.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - backend
          - printer
